### ISSUE TITLE
How can I install this

### ISSUE THREAD

**Issue by soloam** [vigne/node-red-bticino-myhome#1]
Hello, how can I install this into my nodered? There is no package in npm

Thank You

**Comment by vigne** [comment]
Hello,

I didn't make an NPM so far since the library is still "work in progress" and somewhat unfinished, although I use since about 2 years now without major issues. Anyhow, if you like to give it a try, clone the repo in a folder of your choosing and do

 ` npm link node-red-contrib-bticino-myhome`

if `node-red-contrib-bticino-myhome` is the name of the folder you cloned the repo in. After a NodeRED restart you should see the new nodes.

Also, please note that the password authentication is not properly tested, thus it works best if you add your NodeRED host IP to the "trusted networks" in your MyHome configuration.

Hope this helps, if you need any more help, feel free to contact me.

Cheers
